### ISSUE TITLE
Install fails using python 3.7

### ISSUE THREAD

**Issue by CharterMitch** [aristanetworks/robotframework-aristalibrary#32]
(base) C:\>pip install robotframework-aristalibrary
Collecting robotframework-aristalibrary
  Downloading https://files.pythonhosted.org/packages/87/55/c7ca6d201561f567e9aaaff60a74722e02bb018c0cb9efa467c47e427348/robotframework-aristalibrary-1.3.0.tar.gz (70kB)
     |████████████████████████████████| 71kB 353kB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\p2901112\AppData\Local\Temp\pip-install-fgc60kbd\robotframework-aristalibrary\setup.py", line 41, in <module>
        execfile(join(CURDIR, 'AristaLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\p2901112\AppData\Local\Temp\pip-install-fgc60kbd\robotframework-aristalibrary\

**Comment by castroflavio** [comment]
I second this. Python2 is about to not be supported anymore. All users would appreciate if this works with python3

**Comment by CloudAloud** [comment]
Hi,

I just run Python utility 2to3 and fixed one error so library started working for Python 3.10.
Would anyone be interested in that?

**Comment by tetheredge** [comment]
I would be very interested in this library to work in Python 3.

**Comment by CloudAloud** [comment]
> I would be very interested in this library to work in Python 3.

Please check https://github.com/CloudAloud/robotframework-aristalibrary3
It was a while I used it last time and I can't test it so if it doesn't work please try running 2to3 on Python2 code. I also remember I had to fix one issue but I don't remember what exactly.

**Comment by tetheredge** [comment]
>Please check https://github.com/CloudAloud/robotframework-aristalibrary3
It was a while I used it last time and I can't test it so if it doesn't work please try running 2to3 on Python2 code. I also remember I had to fix one issue but I don't remember what exactly.

Thank you for getting back to me on this.  Between the time I noticed this current repo and you posting your statement about the new repo updated for Python3. I forked this repo, made the changes to work in Python3 and fixed some other bugs in the process and got the library working.  I was not trying to take over your effort, but needed this for work at that particular time.

When I have some time I will checkout the new repo and see how it works out.

**Comment by CloudAloud** [comment]
@tetheredge I am glad to hear you made it work on python3. Feel free to make a PR to [new repo](https://github.com/CloudAloud/robotframework-aristalibrary3) so others can use this 6 yo library again :)
